export const TAGGLE_MOBILE_OPEN = 'TAGGLE_MOBILE_OPEN';
export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';
export const CHANGE_TITLE = 'CHANGE_TITLE';
export const UPDATE_DATA = 'UPDATE_DATA';
export const CREATE_ORIGINAL = 'CREATE_ORIGINAL';
export const RESET_DATA = 'RESET_DATA';
export const OPEN_DIALOG = 'OPEN_DIALOG';
